# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

#  node:
#    image: node
#    build: .
#    command: npm run dev
#    restart: unless-stopped
#    ports:
#      - 80:123
#    volumes:
#      - .:/app