# * is behind proxy => localhost
#
# ! not yet tested with new code
# TODO: get port from .env

version: '3'

services:

  node:
    build: .
    hostname: node
    env_file:
      - .env
    environment:
      WAIT_HOSTS: db:3306
    depends_on:
      - db
    command: sh -c "/wait && npx prisma generate && npx prisma db push && npm start"
    restart: unless-stopped
    volumes:
      - .:/usr/app/
    links:
      - "db:database"
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
      - "127.0.0.1:${PORTAPI}:${PORTAPI}"
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  db:
    image: mysql
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
