# * is behind proxy => localhost
#
# ! not yet tested with new code
# TODO: get port from .env

version: '3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 127.0.0.1:3306:3306

  node:
    build: .
    command: npm start
    restart: unless-stopped
    volumes:
      - .:/usr/app/
    ports:
      - 127.0.0.1:3050:3050
